/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.graphcalc;
import java.awt.Graphics;
/**
 *
 * @author Adiyan Ahmed
 */
public class GraphCalcUI extends javax.swing.JDialog {

    /**
     * Creates new form GraphCalcUI
     */
    public GraphCalcUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        graphCalcUI = new javax.swing.JPanel();
        fxLabel = new javax.swing.JLabel();
        x5Label = new javax.swing.JLabel();
        x4Label = new javax.swing.JLabel();
        x3Label = new javax.swing.JLabel();
        x2Label = new javax.swing.JLabel();
        x1Label = new javax.swing.JLabel();
        x5Text = new javax.swing.JTextField();
        x4Text = new javax.swing.JTextField();
        x3Text = new javax.swing.JTextField();
        x2Text = new javax.swing.JTextField();
        x1Text = new javax.swing.JTextField();
        x0Text = new javax.swing.JTextField();
        graphButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        graphImage = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Graphing Calculator"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        graphCalcUI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graphing Calculator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 2, 18), new java.awt.Color(255, 0, 51))); // NOI18N

        fxLabel.setText("f(x) =");

        x5Label.setText("x^5 +");

        x4Label.setText("x^4 +");

        x3Label.setText("x^3 +");

        x2Label.setText("x^2 +");

        x1Label.setText("x +");

        x5Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x5TextActionPerformed(evt);
            }
        });

        x4Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x4TextActionPerformed(evt);
            }
        });

        x3Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3TextActionPerformed(evt);
            }
        });

        x2Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2TextActionPerformed(evt);
            }
        });

        x1Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1TextActionPerformed(evt);
            }
        });

        x0Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x0TextActionPerformed(evt);
            }
        });

        graphButton.setText("Graph");
        graphButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graphButtonMouseClicked(evt);
            }
        });
        graphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        graphImage.setBackground(new java.awt.Color(255, 255, 255));
        graphImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graphImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout graphImageLayout = new javax.swing.GroupLayout(graphImage);
        graphImage.setLayout(graphImageLayout);
        graphImageLayout.setHorizontalGroup(
            graphImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        graphImageLayout.setVerticalGroup(
            graphImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graphCalcUILayout = new javax.swing.GroupLayout(graphCalcUI);
        graphCalcUI.setLayout(graphCalcUILayout);
        graphCalcUILayout.setHorizontalGroup(
            graphCalcUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphCalcUILayout.createSequentialGroup()
                .addGroup(graphCalcUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(graphCalcUILayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(graphCalcUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(graphImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitButton)))
                    .addGroup(graphCalcUILayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(graphCalcUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(graphCalcUILayout.createSequentialGroup()
                                .addComponent(fxLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x5Text, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x5Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x4Text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x4Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(x3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x0Text, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(graphCalcUILayout.createSequentialGroup()
                                .addComponent(graphButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearButton)))))
                .addGap(0, 0, 0))
        );
        graphCalcUILayout.setVerticalGroup(
            graphCalcUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphCalcUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graphCalcUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fxLabel)
                    .addComponent(x5Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x5Label)
                    .addComponent(x4Label)
                    .addComponent(x3Label)
                    .addComponent(x2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x2Label)
                    .addComponent(x1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1Label)
                    .addComponent(x0Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(graphCalcUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(graphButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(graphCalcUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphCalcUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void x5TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x5TextActionPerformed
      
    }//GEN-LAST:event_x5TextActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
System.exit(0);   //exit button  
    }//GEN-LAST:event_exitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

    }//GEN-LAST:event_clearButtonActionPerformed

    private void graphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphButtonActionPerformed

    }//GEN-LAST:event_graphButtonActionPerformed

    private void graphImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphImageMouseClicked

    }//GEN-LAST:event_graphImageMouseClicked

//CALLING CODE!
    private void graphButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphButtonMouseClicked

//showing the jPanel where the graph is to be displayed 
Graphics g = graphImage.getGraphics();
graphImage.setVisible(true);
g.drawLine(10, 260, 510, 260); //x-axis
g.drawLine(260, 10, 260, 510); //y-axis

//CREATING CARTESIAN PLANE ON J-PANEL
//ticks on x-axis
for(int xLineVal = 10; xLineVal <= 510; xLineVal = xLineVal + 25){
    g.drawLine(xLineVal, 255, xLineVal, 265);
}

//ticks on y-axis
for(int yLineVal = 10; yLineVal <= 510; yLineVal = yLineVal + 25){
    g.drawLine(255, yLineVal, 265, yLineVal);
}

//scale for x-axis 
int tickTextX_xVal = 7;
for(int tickNumX = -10; tickNumX <= 10; tickNumX = tickNumX + 1){
    String tickTextX = String.valueOf(tickNumX);
    g.drawString(tickTextX, tickTextX_xVal, 280);
    tickTextX_xVal = tickTextX_xVal + 25;
            }

//scale for y-axis (-10 - -1)
int tickTextY_yVal = 15;
for(int tickNumY = 10; tickNumY >= 1; tickNumY = tickNumY - 1){
    String tickTextY = String.valueOf(tickNumY);
    g.drawString(tickTextY, 270, tickTextY_yVal);
    tickTextY_yVal = tickTextY_yVal + 25;
            }

//scale for y-axis (1 - 10)
int tickTextY_yVal2 = 290;
for(int tickNumY2 = -1; tickNumY2 >= -10; tickNumY2 = tickNumY2 - 1){
    String tickTextY2 = String.valueOf(tickNumY2);
    g.drawString(tickTextY2, 270, tickTextY_yVal2);
    tickTextY_yVal2 = tickTextY_yVal2 + 25;
            }

//CREATING ARRAY TO RETRIEVE INFORMATION FROM TEXT BOXES
double [] theArray = new double[6];
theArray[5] = Float.parseFloat(x0Text.getText());
theArray[4] = Float.parseFloat(x1Text.getText());
theArray[3] = Float.parseFloat(x2Text.getText());
theArray[2] = Float.parseFloat(x3Text.getText());
theArray[1] = Float.parseFloat(x4Text.getText());
theArray[0] = Float.parseFloat(x5Text.getText());

//DRAWING THE GRAPH
int xC = 10; //counter for x-value (pixels)

for(double xVal = -10.0; xVal <= 10; xVal = xVal + 0.04){
double yVal = funcVal(xVal, theArray);
int yC = (int) ((yVal * 25 * -1) + 260);

//calculating values for rect command (to connect ovals for smoother look)
double nextY = funcVal(xVal + 0.04, theArray); 
int nextYC = (int) (nextY * 25 * -1) + 260;
int height = Math.abs(nextYC - yC);

//using ovals and rectangles to create curve 
if((yC > 0) && (yC < 500)){
    g.fillOval(xC, yC, 4, 4);
    g.fillRect(xC, yC, 4, height);           
}
xC = xC + 1; 
} 

    }//GEN-LAST:event_graphButtonMouseClicked

/*
@param xVal
@param exponents
@return yVal
 */
    
//calculating the y-value
private static double funcVal(double xVal, double theArray[]){
     double yVal = 0.0;
     int exponent = 5;
     double curVal;
          
for(int arrayIndex = 0; arrayIndex <= 4; arrayIndex++){
    curVal = theArray[arrayIndex]*Math.pow(xVal, exponent); 
    exponent = exponent - 1;
    yVal = yVal + curVal;
    }
     
 yVal = yVal + theArray[5];     
     return (yVal);
    }    
    
    
    private void x0TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x0TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x0TextActionPerformed

    private void x1TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1TextActionPerformed

    private void x2TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2TextActionPerformed

    private void x3TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x3TextActionPerformed

    private void x4TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x4TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x4TextActionPerformed

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        //clears the jPanel and resets values to 0 
        graphImage.setVisible(false);
        x5Text.setText("0");
        x4Text.setText("0");
        x3Text.setText("0");
        x2Text.setText("0");
        x1Text.setText("0");
        x0Text.setText("0");
        graphImage.setVisible(true); //creates fresh jPanel with no graph
    }//GEN-LAST:event_clearButtonMouseClicked

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphCalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphCalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphCalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphCalcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GraphCalcUI dialog = new GraphCalcUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel fxLabel;
    private javax.swing.JButton graphButton;
    private javax.swing.JPanel graphCalcUI;
    private javax.swing.JPanel graphImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField x0Text;
    private javax.swing.JLabel x1Label;
    private javax.swing.JTextField x1Text;
    private javax.swing.JLabel x2Label;
    private javax.swing.JTextField x2Text;
    private javax.swing.JLabel x3Label;
    private javax.swing.JTextField x3Text;
    private javax.swing.JLabel x4Label;
    private javax.swing.JTextField x4Text;
    private javax.swing.JLabel x5Label;
    private javax.swing.JTextField x5Text;
    // End of variables declaration//GEN-END:variables
}
